# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class MainWindow(object):
    def __init__(self):
        import sys
        app = QtWidgets.QApplication(sys.argv)
        main_window = QtWidgets.QMainWindow()
        self.create_objects(main_window)
        self.setupUi(main_window)
        main_window.show()
        app.exec_()

    def create_objects(self, main_window):
        self.central_widget = QtWidgets.QWidget(main_window)
        self.status_bar = QtWidgets.QStatusBar(main_window)
        self.menu_bar = QtWidgets.QMenuBar(main_window)
        self.cancel_btn = QtWidgets.QPushButton(self.central_widget)
        self.pause_btn = QtWidgets.QPushButton(self.central_widget)
        self.resume_btn = QtWidgets.QPushButton(self.central_widget)
        self.logo_btn = QtWidgets.QLabel(self.central_widget)
        self.tray = {}
        for i in range(1, 7):
            self.tray[i] = {}
            self.tray[i]['frame'] = QtWidgets.QFrame(self.central_widget)
            self.tray[i]['cmd_btn'] = QtWidgets.QPushButton(self.tray[i]['frame'])
            self.tray[i]['assn_serial_btn'] = QtWidgets.QPushButton(self.tray[i]['frame'])
            self.tray[i]['assn_mac_btn'] = QtWidgets.QPushButton(self.tray[i]['frame'])
            self.tray[i]['status'] = QtWidgets.QLabel(self.tray[i]['frame'])
            self.tray[i]['test_counter'] = QtWidgets.QLabel(self.tray[i]['frame'])
            self.tray[i]['board_label'] = QtWidgets.QLabel(self.tray[i]['frame'])
            self.tray[i]['info_btn'] = QtWidgets.QPushButton(self.tray[i]['frame'])
            self.tray[i]['debug'] = QtWidgets.QLabel(self.tray[i]['frame'])
            self.tray[i]['progress'] = QtWidgets.QProgressBar(self.tray[i]['frame'])
            self.tray[i]['label'] = QtWidgets.QLabel(self.tray[i]['frame'])

    def setupUi(self, main_window):
        main_window.setObjectName("MainWindow")
        main_window.resize(1235, 650)
        self.central_widget.setObjectName("centralWidget")
        self.logo_btn.setGeometry(QtCore.QRect(20, 10, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Antema")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.logo_btn.setFont(font)
        self.logo_btn.setObjectName("logo_btn")
        self.resume_btn.setGeometry(QtCore.QRect(630, 20, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.resume_btn.setFont(font)
        self.resume_btn.setObjectName("resume_btn")
        self.pause_btn.setGeometry(QtCore.QRect(830, 20, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pause_btn.setFont(font)
        self.pause_btn.setObjectName("pause_btn")
        self.cancel_btn.setGeometry(QtCore.QRect(1030, 20, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setObjectName("cancel_btn")
        self.tray[1]['frame'].setGeometry(QtCore.QRect(40, 80, 571, 171))
        self.tray[1]['frame'].setStyleSheet("border: 1px solid black;")
        self.tray[1]['frame'].setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tray[1]['frame'].setFrameShadow(QtWidgets.QFrame.Raised)
        self.tray[1]['frame'].setObjectName("tray1")
        self.tray[1]['label'].setGeometry(QtCore.QRect(490, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Antema")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tray[1]['label'].setFont(font)
        self.tray[1]['label'].setStyleSheet("background-color: rgba(218, 218, 218, 200); border: none;")
        self.tray[1]['label'].setObjectName("tray1_label")
        self.tray[1]['progress'].setGeometry(QtCore.QRect(20, 133, 541, 20))
        self.tray[1]['progress'].setProperty("value", 80)
        self.tray[1]['progress'].setTextVisible(False)
        self.tray[1]['progress'].setOrientation(QtCore.Qt.Horizontal)
        self.tray[1]['progress'].setInvertedAppearance(False)
        self.tray[1]['progress'].setObjectName("tray1_progress")
        self.tray[1]['debug'].setGeometry(QtCore.QRect(20, 100, 351, 21))
        self.tray[1]['debug'].setStyleSheet("border: none; background: white; padding: 0 2px;")
        self.tray[1]['debug'].setObjectName("tray1_debug")
        self.tray[1]['info_btn'].setGeometry(QtCore.QRect(480, 100, 75, 23))
        self.tray[1]['info_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[1]['info_btn'].setObjectName("tray1_info_btn")
        self.tray[1]['cmd_btn'].setGeometry(QtCore.QRect(390, 100, 75, 23))
        self.tray[1]['cmd_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[1]['cmd_btn'].setObjectName("tray1_cmd_btn")
        self.tray[1]['board_label'].setGeometry(QtCore.QRect(20, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Antema")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.tray[1]['board_label'].setFont(font)
        self.tray[1]['board_label'].setStyleSheet("border: none;")
        self.tray[1]['board_label'].setObjectName("tray1_board_label")
        self.tray[1]['test_counter'].setGeometry(QtCore.QRect(20, 60, 175, 21))
        self.tray[1]['test_counter'].setStyleSheet("border: none; padding: 0 2px;")
        self.tray[1]['test_counter'].setObjectName("tray1_test_counter")
        self.tray[1]['status'].setGeometry(QtCore.QRect(20, 40, 175, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tray[1]['status'].setFont(font)
        self.tray[1]['status'].setStyleSheet("border: none; padding: 0 2px;")
        self.tray[1]['status'].setObjectName("tray1_status")
        self.tray[1]['assn_mac_btn'].setGeometry(QtCore.QRect(390, 70, 75, 23))
        self.tray[1]['assn_mac_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[1]['assn_mac_btn'].setObjectName("tray1_assn_mac_btn")
        self.tray[1]['assn_serial_btn'].setGeometry(QtCore.QRect(480, 70, 75, 23))
        self.tray[1]['assn_serial_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[1]['assn_serial_btn'].setObjectName("tray1_assn_serial_btn")
        self.tray[2]['frame'].setGeometry(QtCore.QRect(40, 260, 571, 171))
        self.tray[2]['frame'].setStyleSheet("border: 1px solid black;")
        self.tray[2]['frame'].setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tray[2]['frame'].setFrameShadow(QtWidgets.QFrame.Raised)
        self.tray[2]['frame'].setObjectName("tray2")
        self.tray[2]['label'].setGeometry(QtCore.QRect(490, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Antema")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tray[2]['label'].setFont(font)
        self.tray[2]['label'].setStyleSheet("background-color: rgba(218, 218, 218, 200); border: none;")
        self.tray[2]['label'].setObjectName("tray2_label")
        self.tray[2]['progress'].setGeometry(QtCore.QRect(20, 133, 541, 20))
        self.tray[2]['progress'].setProperty("value", 80)
        self.tray[2]['progress'].setTextVisible(False)
        self.tray[2]['progress'].setOrientation(QtCore.Qt.Horizontal)
        self.tray[2]['progress'].setInvertedAppearance(False)
        self.tray[2]['progress'].setObjectName("tray2_progress")
        self.tray[2]['debug'].setGeometry(QtCore.QRect(20, 100, 351, 21))
        self.tray[2]['debug'].setStyleSheet("border: none; background: white; padding: 0 2px;")
        self.tray[2]['debug'].setObjectName("tray2_debug")
        self.tray[2]['info_btn'].setGeometry(QtCore.QRect(480, 100, 75, 23))
        self.tray[2]['info_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[2]['info_btn'].setObjectName("tray2_info_btn")
        self.tray[2]['cmd_btn'].setGeometry(QtCore.QRect(390, 100, 75, 23))
        self.tray[2]['cmd_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[2]['cmd_btn'].setObjectName("tray2_cmd_btn")
        self.tray[2]['board_label'].setGeometry(QtCore.QRect(20, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Antema")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.tray[2]['board_label'].setFont(font)
        self.tray[2]['board_label'].setStyleSheet("border: none;")
        self.tray[2]['board_label'].setObjectName("tray2_board_label")
        self.tray[2]['test_counter'].setGeometry(QtCore.QRect(20, 60, 175, 21))
        self.tray[2]['test_counter'].setStyleSheet("border: none; padding: 0 2px;")
        self.tray[2]['test_counter'].setObjectName("tray2_test_counter")
        self.tray[2]['status'].setGeometry(QtCore.QRect(20, 40, 175, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tray[2]['status'].setFont(font)
        self.tray[2]['status'].setStyleSheet("border: none; padding: 0 2px;")
        self.tray[2]['status'].setObjectName("tray2_status")
        self.tray[2]['assn_mac_btn'].setGeometry(QtCore.QRect(390, 70, 75, 23))
        self.tray[2]['assn_mac_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[2]['assn_mac_btn'].setObjectName("tray2_assn_mac_btn")
        self.tray[2]['assn_serial_btn'].setGeometry(QtCore.QRect(480, 70, 75, 23))
        self.tray[2]['assn_serial_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[2]['assn_serial_btn'].setObjectName("tray2_assn_serial_btn")
        self.tray[3]['frame'].setGeometry(QtCore.QRect(40, 440, 571, 171))
        self.tray[3]['frame'].setStyleSheet("border: 1px solid black;")
        self.tray[3]['frame'].setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tray[3]['frame'].setFrameShadow(QtWidgets.QFrame.Raised)
        self.tray[3]['frame'].setObjectName("tray3")
        self.tray[3]['label'].setGeometry(QtCore.QRect(490, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Antema")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tray[3]['label'].setFont(font)
        self.tray[3]['label'].setStyleSheet("background-color: rgba(218, 218, 218, 200); border: none;")
        self.tray[3]['label'].setObjectName("tray3_label")
        self.tray[3]['progress'].setGeometry(QtCore.QRect(20, 133, 541, 20))
        self.tray[3]['progress'].setProperty("value", 80)
        self.tray[3]['progress'].setTextVisible(False)
        self.tray[3]['progress'].setOrientation(QtCore.Qt.Horizontal)
        self.tray[3]['progress'].setInvertedAppearance(False)
        self.tray[3]['progress'].setObjectName("tray3_progress")
        self.tray[3]['debug'].setGeometry(QtCore.QRect(20, 100, 351, 21))
        self.tray[3]['debug'].setStyleSheet("border: none; background: white; padding: 0 2px;")
        self.tray[3]['debug'].setObjectName("tray3_debug")
        self.tray[3]['info_btn'].setGeometry(QtCore.QRect(480, 100, 75, 23))
        self.tray[3]['info_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[3]['info_btn'].setObjectName("tray3_info_btn")
        self.tray[3]['cmd_btn'].setGeometry(QtCore.QRect(390, 100, 75, 23))
        self.tray[3]['cmd_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[3]['cmd_btn'].setObjectName("tray3_cmd_btn")
        self.tray[3]['board_label'].setGeometry(QtCore.QRect(20, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Antema")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.tray[3]['board_label'].setFont(font)
        self.tray[3]['board_label'].setStyleSheet("border: none;")
        self.tray[3]['board_label'].setObjectName("tray3_board_label")
        self.tray[3]['test_counter'].setGeometry(QtCore.QRect(20, 60, 175, 21))
        self.tray[3]['test_counter'].setStyleSheet("border: none; padding: 0 2px;")
        self.tray[3]['test_counter'].setObjectName("tray3_test_counter")
        self.tray[3]['status'].setGeometry(QtCore.QRect(20, 40, 175, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tray[3]['status'].setFont(font)
        self.tray[3]['status'].setStyleSheet("border: none; padding: 0 2px;")
        self.tray[3]['status'].setObjectName("tray3_status")
        self.tray[3]['assn_mac_btn'].setGeometry(QtCore.QRect(390, 70, 75, 23))
        self.tray[3]['assn_mac_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[3]['assn_mac_btn'].setObjectName("tray3_assn_mac_btn")
        self.tray[3]['assn_serial_btn'].setGeometry(QtCore.QRect(480, 70, 75, 23))
        self.tray[3]['assn_serial_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[3]['assn_serial_btn'].setObjectName("tray3_assn_serial_btn")
        self.tray[4]['frame'].setGeometry(QtCore.QRect(630, 80, 571, 171))
        self.tray[4]['frame'].setStyleSheet("border: 1px solid black;")
        self.tray[4]['frame'].setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tray[4]['frame'].setFrameShadow(QtWidgets.QFrame.Raised)
        self.tray[4]['frame'].setObjectName("tray4")
        self.tray[4]['label'].setGeometry(QtCore.QRect(490, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Antema")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tray[4]['label'].setFont(font)
        self.tray[4]['label'].setStyleSheet("background-color: rgba(218, 218, 218, 200); border: none;")
        self.tray[4]['label'].setObjectName("tray4_label")
        self.tray[4]['progress'].setGeometry(QtCore.QRect(20, 133, 541, 20))
        self.tray[4]['progress'].setProperty("value", 80)
        self.tray[4]['progress'].setTextVisible(False)
        self.tray[4]['progress'].setOrientation(QtCore.Qt.Horizontal)
        self.tray[4]['progress'].setInvertedAppearance(False)
        self.tray[4]['progress'].setObjectName("tray4_progress")
        self.tray[4]['debug'].setGeometry(QtCore.QRect(20, 100, 351, 21))
        self.tray[4]['debug'].setStyleSheet("border: none; background: white; padding: 0 2px;")
        self.tray[4]['debug'].setObjectName("tray4_debug")
        self.tray[4]['info_btn'].setGeometry(QtCore.QRect(480, 100, 75, 23))
        self.tray[4]['info_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[4]['info_btn'].setObjectName("tray4_info_btn")
        self.tray[4]['cmd_btn'].setGeometry(QtCore.QRect(390, 100, 75, 23))
        self.tray[4]['cmd_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[4]['cmd_btn'].setObjectName("tray4_cmd_btn")
        self.tray[4]['board_label'].setGeometry(QtCore.QRect(20, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Antema")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.tray[4]['board_label'].setFont(font)
        self.tray[4]['board_label'].setStyleSheet("border: none;")
        self.tray[4]['board_label'].setObjectName("tray4_board_label")
        self.tray[4]['test_counter'].setGeometry(QtCore.QRect(20, 60, 175, 21))
        self.tray[4]['test_counter'].setStyleSheet("border: none; padding: 0 2px;")
        self.tray[4]['test_counter'].setObjectName("tray4_test_counter")
        self.tray[4]['status'].setGeometry(QtCore.QRect(20, 40, 175, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tray[4]['status'].setFont(font)
        self.tray[4]['status'].setStyleSheet("border: none; padding: 0 2px;")
        self.tray[4]['status'].setObjectName("tray4_status")
        self.tray[4]['assn_mac_btn'].setGeometry(QtCore.QRect(390, 70, 75, 23))
        self.tray[4]['assn_mac_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[4]['assn_mac_btn'].setObjectName("tray4_assn_mac_btn")
        self.tray[4]['assn_serial_btn'].setGeometry(QtCore.QRect(480, 70, 75, 23))
        self.tray[4]['assn_serial_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[4]['assn_serial_btn'].setObjectName("tray4_assn_serial_btn")
        self.tray[5]['frame'].setGeometry(QtCore.QRect(630, 260, 571, 171))
        self.tray[5]['frame'].setStyleSheet("border: 1px solid black;")
        self.tray[5]['frame'].setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tray[5]['frame'].setFrameShadow(QtWidgets.QFrame.Raised)
        self.tray[5]['frame'].setObjectName("tray5")
        self.tray[5]['label'].setGeometry(QtCore.QRect(490, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Antema")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tray[5]['label'].setFont(font)
        self.tray[5]['label'].setStyleSheet("background-color: rgba(218, 218, 218, 200); border: none;")
        self.tray[5]['label'].setObjectName("tray5_label")
        self.tray[5]['progress'].setGeometry(QtCore.QRect(20, 133, 541, 20))
        self.tray[5]['progress'].setProperty("value", 80)
        self.tray[5]['progress'].setTextVisible(False)
        self.tray[5]['progress'].setOrientation(QtCore.Qt.Horizontal)
        self.tray[5]['progress'].setInvertedAppearance(False)
        self.tray[5]['progress'].setObjectName("tray5_progress")
        self.tray[5]['debug'].setGeometry(QtCore.QRect(20, 100, 351, 21))
        self.tray[5]['debug'].setStyleSheet("border: none; background: white; padding: 0 2px;")
        self.tray[5]['debug'].setObjectName("tray5_debug")
        self.tray[5]['info_btn'].setGeometry(QtCore.QRect(480, 100, 75, 23))
        self.tray[5]['info_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[5]['info_btn'].setObjectName("tray5_info_btn")
        self.tray[5]['cmd_btn'].setGeometry(QtCore.QRect(390, 100, 75, 23))
        self.tray[5]['cmd_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[5]['cmd_btn'].setObjectName("tray5_cmd_btn")
        self.tray[5]['board_label'].setGeometry(QtCore.QRect(20, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Antema")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.tray[5]['board_label'].setFont(font)
        self.tray[5]['board_label'].setStyleSheet("border: none;")
        self.tray[5]['board_label'].setObjectName("tray5_board_label")
        self.tray[5]['test_counter'].setGeometry(QtCore.QRect(20, 60, 175, 21))
        self.tray[5]['test_counter'].setStyleSheet("border: none; padding: 0 2px;")
        self.tray[5]['test_counter'].setObjectName("tray5_test_counter")
        self.tray[5]['status'].setGeometry(QtCore.QRect(20, 40, 175, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tray[5]['status'].setFont(font)
        self.tray[5]['status'].setStyleSheet("border: none; padding: 0 2px;")
        self.tray[5]['status'].setObjectName("tray5_status")
        self.tray[5]['assn_mac_btn'].setGeometry(QtCore.QRect(390, 70, 75, 23))
        self.tray[5]['assn_mac_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[5]['assn_mac_btn'].setObjectName("tray5_assn_mac_btn")
        self.tray[5]['assn_serial_btn'].setGeometry(QtCore.QRect(480, 70, 75, 23))
        self.tray[5]['assn_serial_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[5]['assn_serial_btn'].setObjectName("tray5_assn_serial_btn")
        self.tray[6]['frame'].setGeometry(QtCore.QRect(630, 440, 571, 171))
        self.tray[6]['frame'].setStyleSheet("border: 1px solid black;")
        self.tray[6]['frame'].setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tray[6]['frame'].setFrameShadow(QtWidgets.QFrame.Raised)
        self.tray[6]['frame'].setObjectName("tray6")
        self.tray[6]['label'].setGeometry(QtCore.QRect(490, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Antema")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tray[6]['label'].setFont(font)
        self.tray[6]['label'].setStyleSheet("background-color: rgba(218, 218, 218, 200); border: none;")
        self.tray[6]['label'].setObjectName("tray6_label")
        self.tray[6]['progress'].setGeometry(QtCore.QRect(20, 133, 541, 20))
        self.tray[6]['progress'].setProperty("value", 80)
        self.tray[6]['progress'].setTextVisible(False)
        self.tray[6]['progress'].setOrientation(QtCore.Qt.Horizontal)
        self.tray[6]['progress'].setInvertedAppearance(False)
        self.tray[6]['progress'].setObjectName("tray6_progress")
        self.tray[6]['debug'].setGeometry(QtCore.QRect(20, 100, 351, 21))
        self.tray[6]['debug'].setStyleSheet("border: none; background: white; padding: 0 2px;")
        self.tray[6]['debug'].setObjectName("tray6_debug")
        self.tray[6]['info_btn'].setGeometry(QtCore.QRect(480, 100, 75, 23))
        self.tray[6]['info_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[6]['info_btn'].setObjectName("tray6_info_btn")
        self.tray[6]['cmd_btn'].setGeometry(QtCore.QRect(390, 100, 75, 23))
        self.tray[6]['cmd_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[6]['cmd_btn'].setObjectName("tray6_cmd_btn")
        self.tray[6]['board_label'].setGeometry(QtCore.QRect(20, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Antema")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.tray[6]['board_label'].setFont(font)
        self.tray[6]['board_label'].setStyleSheet("border: none;")
        self.tray[6]['board_label'].setObjectName("tray6_board_label")
        self.tray[6]['test_counter'].setGeometry(QtCore.QRect(20, 60, 175, 21))
        self.tray[6]['test_counter'].setStyleSheet("border: none; padding: 0 2px;")
        self.tray[6]['test_counter'].setObjectName("tray6_test_counter")
        self.tray[6]['status'].setGeometry(QtCore.QRect(20, 40, 175, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tray[6]['status'].setFont(font)
        self.tray[6]['status'].setStyleSheet("border: none; padding: 0 2px;")
        self.tray[6]['status'].setObjectName("tray6_status")
        self.tray[6]['assn_mac_btn'].setGeometry(QtCore.QRect(390, 70, 75, 23))
        self.tray[6]['assn_mac_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[6]['assn_mac_btn'].setObjectName("tray6_assn_mac_btn")
        self.tray[6]['assn_serial_btn'].setGeometry(QtCore.QRect(480, 70, 75, 23))
        self.tray[6]['assn_serial_btn'].setStyleSheet("background-color: rgb(225, 225, 225);")
        self.tray[6]['assn_serial_btn'].setObjectName("tray6_assn_serial_btn")
        main_window.setCentralWidget(self.central_widget)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 1289, 21))
        self.menu_bar.setObjectName("menu_bar")
        main_window.setMenuBar(self.menu_bar)
        self.status_bar.setObjectName("status_bar")
        main_window.setStatusBar(self.status_bar)
        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "SeaLion Control"))
        self.logo_btn.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">SeaLion</p></body></html>"))
        self.resume_btn.setText(_translate("MainWindow", "&Resume"))
        self.pause_btn.setText(_translate("MainWindow", "&Pause"))
        self.cancel_btn.setText(_translate("MainWindow", "&Cancel"))
        self.tray[1]['label'].setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Tray 1</p></body></html>"))
        self.tray[1]['debug'].setText(_translate("MainWindow", "Running test: <test name>"))
        self.tray[1]['info_btn'].setText(_translate("MainWindow", "Debug"))
        self.tray[1]['cmd_btn'].setText(_translate("MainWindow", "Cmd"))
        self.tray[1]['board_label'].setText(_translate("MainWindow", "<html><head/><body><p>LD2100</p></body></html>"))
        self.tray[1]['test_counter'].setText(_translate("MainWindow", "Running test: 5/7"))
        self.tray[1]['status'].setText(_translate("MainWindow", "Status: Passing"))
        self.tray[1]['assn_mac_btn'].setText(_translate("MainWindow", "Assn MAC"))
        self.tray[1]['assn_serial_btn'].setText(_translate("MainWindow", "Assn Ser"))
        self.tray[2]['label'].setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Tray 2</p></body></html>"))
        self.tray[2]['debug'].setText(_translate("MainWindow", "Running test: <test name>"))
        self.tray[2]['info_btn'].setText(_translate("MainWindow", "Debug"))
        self.tray[2]['cmd_btn'].setText(_translate("MainWindow", "Cmd"))
        self.tray[2]['board_label'].setText(_translate("MainWindow", "<html><head/><body><p>LD2100</p></body></html>"))
        self.tray[2]['test_counter'].setText(_translate("MainWindow", "Running test: 5/7"))
        self.tray[2]['status'].setText(_translate("MainWindow", "Status: Passing"))
        self.tray[2]['assn_mac_btn'].setText(_translate("MainWindow", "Assn MAC"))
        self.tray[2]['assn_serial_btn'].setText(_translate("MainWindow", "Assn Ser"))
        self.tray[3]['label'].setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Tray 3</p></body></html>"))
        self.tray[3]['debug'].setText(_translate("MainWindow", "Running test: <test name>"))
        self.tray[3]['info_btn'].setText(_translate("MainWindow", "Debug"))
        self.tray[3]['cmd_btn'].setText(_translate("MainWindow", "Cmd"))
        self.tray[3]['board_label'].setText(_translate("MainWindow", "<html><head/><body><p>LD2100</p></body></html>"))
        self.tray[3]['test_counter'].setText(_translate("MainWindow", "Running test: 5/7"))
        self.tray[3]['status'].setText(_translate("MainWindow", "Status: Passing"))
        self.tray[3]['assn_mac_btn'].setText(_translate("MainWindow", "Assn MAC"))
        self.tray[3]['assn_serial_btn'].setText(_translate("MainWindow", "Assn Ser"))
        self.tray[4]['label'].setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Tray 4</p></body></html>"))
        self.tray[4]['debug'].setText(_translate("MainWindow", "Running test: <test name>"))
        self.tray[4]['info_btn'].setText(_translate("MainWindow", "Debug"))
        self.tray[4]['cmd_btn'].setText(_translate("MainWindow", "Cmd"))
        self.tray[4]['board_label'].setText(_translate("MainWindow", "<html><head/><body><p>LD5200</p></body></html>"))
        self.tray[4]['test_counter'].setText(_translate("MainWindow", "Running test: 5/7"))
        self.tray[4]['status'].setText(_translate("MainWindow", "Status: Passing"))
        self.tray[4]['assn_mac_btn'].setText(_translate("MainWindow", "Assn MAC"))
        self.tray[4]['assn_serial_btn'].setText(_translate("MainWindow", "Assn Ser"))
        self.tray[5]['label'].setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Tray 5</p></body></html>"))
        self.tray[5]['debug'].setText(_translate("MainWindow", "Running test: <test name>"))
        self.tray[5]['info_btn'].setText(_translate("MainWindow", "Debug"))
        self.tray[5]['cmd_btn'].setText(_translate("MainWindow", "Cmd"))
        self.tray[5]['board_label'].setText(_translate("MainWindow", "<html><head/><body><p>LD5200</p></body></html>"))
        self.tray[5]['test_counter'].setText(_translate("MainWindow", "Running test: 5/7"))
        self.tray[5]['status'].setText(_translate("MainWindow", "Status: Passing"))
        self.tray[5]['assn_mac_btn'].setText(_translate("MainWindow", "Assn MAC"))
        self.tray[5]['assn_serial_btn'].setText(_translate("MainWindow", "Assn Ser"))
        self.tray[6]['label'].setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Tray 6</p></body></html>"))
        self.tray[6]['debug'].setText(_translate("MainWindow", "Running test: <test name>"))
        self.tray[6]['info_btn'].setText(_translate("MainWindow", "Debug"))
        self.tray[6]['cmd_btn'].setText(_translate("MainWindow", "Cmd"))
        self.tray[6]['board_label'].setText(_translate("MainWindow", "<html><head/><body><p>LD5200</p></body></html>"))
        self.tray[6]['test_counter'].setText(_translate("MainWindow", "Running test: 5/7"))
        self.tray[6]['status'].setText(_translate("MainWindow", "Status: Passing"))
        self.tray[6]['assn_mac_btn'].setText(_translate("MainWindow", "Assn MAC"))
        self.tray[6]['assn_serial_btn'].setText(_translate("MainWindow", "Assn Ser"))

if __name__ == "__main__":
    ui = MainWindow()
